# typed: false
# frozen_string_literal: true

# GENERATED by render-formula.sh in goedelsoup/yidam. Do not edit by hand —
# the next release overwrites this file. Fix the generator instead.
#
# A binary formula, not a source one. The whole point of the tap is to skip a
# compile: the light `reports` build is what ships, and `--features full`
# (index-build, serve --mcp, the sqlite/rdf exports) remains a source build
# because it needs protoc and an ONNX runtime.
class Yidam < Formula
  desc "Corpus analysis and index CLI for yidam-derived repositories"
  homepage "https://github.com/goedelsoup/yidam"
  version "0.6.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/goedelsoup/yidam/releases/download/cli/v0.6.0/yidam-0.6.0-aarch64-apple-darwin.tar.gz"
      sha256 "ccd55bfd6a120c36275400640137026b1b4da10c23e99a07f60b93f194647848"
    end
    on_intel do
      url "https://github.com/goedelsoup/yidam/releases/download/cli/v0.6.0/yidam-0.6.0-x86_64-apple-darwin.tar.gz"
      sha256 "bb365220f846ac94c1cfff0fe7de0055e39a497f96fc05260b400c447552f255"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/goedelsoup/yidam/releases/download/cli/v0.6.0/yidam-0.6.0-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "c99150a90048455fd4241c79dc95130b3d2b12072741a470b397b6e55a08d3e6"
    end
    on_intel do
      url "https://github.com/goedelsoup/yidam/releases/download/cli/v0.6.0/yidam-0.6.0-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "45fa9293c537f691624b277a08d9f8042ce4415b246197087410eacf33671feb"
    end
  end

  # The tarball holds a single `yidam-<version>-<target>/` directory, which
  # Homebrew strips on unpack, so the binary and LICENSE are at the staging root.
  def install
    bin.install "yidam"
  end

  # `--version` names the version, the build commit, and the compiled feature
  # set. Asserting the version is what catches the failure this formula is most
  # able to cause on its own: a url and a version that disagree, which installs
  # a binary that is not the one the formula claims.
  test do
    assert_match version.to_s, shell_output("#{bin}/yidam --version")
  end
end
