# typed: false
# frozen_string_literal: true

# GENERATED by render-formula.sh in goedelsoup/yidam. Do not edit by hand —
# the next release overwrites this file. Fix the generator instead.
#
# A binary formula, not a source one. The whole point of the tap is to skip a
# compile: the light `reports` build is what ships, and `--features full`
# (index-build, serve --mcp, the sqlite/rdf exports) remains a source build
# because it needs protoc and an ONNX runtime.
class Yidam < Formula
  desc "Corpus analysis and index CLI for yidam-derived repositories"
  homepage "https://github.com/goedelsoup/yidam"
  version "0.12.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/goedelsoup/yidam/releases/download/cli/v0.12.0/yidam-0.12.0-aarch64-apple-darwin.tar.gz"
      sha256 "efe5655ef80374502df98d8dc08e8f106ad37cd2eaefbad22b92e3046a87a20f"
    end
    on_intel do
      url "https://github.com/goedelsoup/yidam/releases/download/cli/v0.12.0/yidam-0.12.0-x86_64-apple-darwin.tar.gz"
      sha256 "ed19ba00cc8f9895eedaaa663d516351fcdcb966496dfe36ee36ef6b2fd556c6"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/goedelsoup/yidam/releases/download/cli/v0.12.0/yidam-0.12.0-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "e2e47b4de8c40c793a1b7c40068c488c901b0debe4f630ce0dc271b8e92628ce"
    end
    on_intel do
      url "https://github.com/goedelsoup/yidam/releases/download/cli/v0.12.0/yidam-0.12.0-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "bf4ca96a584219c2c83e0310d41fb1e1e8b8bb7b8c765ab9ef1d46b21e6a6e58"
    end
  end

  # The tarball holds a single `yidam-<version>-<target>/` directory, which
  # Homebrew strips on unpack, so the binary and LICENSE are at the staging root.
  def install
    bin.install "yidam"
  end

  # `--version` names the version, the build commit, and the compiled feature
  # set. Asserting the version is what catches the failure this formula is most
  # able to cause on its own: a url and a version that disagree, which installs
  # a binary that is not the one the formula claims.
  test do
    assert_match version.to_s, shell_output("#{bin}/yidam --version")
  end
end
