# typed: false
# frozen_string_literal: true

# GENERATED by render-formula.sh in goedelsoup/yidam. Do not edit by hand —
# the next release overwrites this file. Fix the generator instead.
#
# A binary formula, not a source one. The whole point of the tap is to skip a
# compile: the light `reports` build is what ships, and `--features full`
# (index-build, serve --mcp, the sqlite/rdf exports) remains a source build
# because it needs protoc and an ONNX runtime.
class Yidam < Formula
  desc "Corpus analysis and index CLI for yidam-derived repositories"
  homepage "https://github.com/goedelsoup/yidam"
  version "0.5.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/goedelsoup/yidam/releases/download/cli/v0.5.0/yidam-0.5.0-aarch64-apple-darwin.tar.gz"
      sha256 "aa5123b067b951c8485a1b812c801238a2d9d4266d1599072658125871a9234c"
    end
    on_intel do
      url "https://github.com/goedelsoup/yidam/releases/download/cli/v0.5.0/yidam-0.5.0-x86_64-apple-darwin.tar.gz"
      sha256 "90992141a05f958cb89967b19fb24b4afe1e887eeeb5ff48ad9d362a75de4de9"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/goedelsoup/yidam/releases/download/cli/v0.5.0/yidam-0.5.0-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "97659f06e1776ea68ff11902c93422b6d0a84bb87bb9c3030a1a63045832f8f7"
    end
    on_intel do
      url "https://github.com/goedelsoup/yidam/releases/download/cli/v0.5.0/yidam-0.5.0-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "f3bf408b4e93c681435ffe6b6538cc7922fbd0859c993d4f9eca60723c99db98"
    end
  end

  # The tarball holds a single `yidam-<version>-<target>/` directory, which
  # Homebrew strips on unpack, so the binary and LICENSE are at the staging root.
  def install
    bin.install "yidam"
  end

  # `--version` names the version, the build commit, and the compiled feature
  # set. Asserting the version is what catches the failure this formula is most
  # able to cause on its own: a url and a version that disagree, which installs
  # a binary that is not the one the formula claims.
  test do
    assert_match version.to_s, shell_output("#{bin}/yidam --version")
  end
end
